# Generated by Django 5.1.2 on 2024-10-16 00:38

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('in_stock', 'Estoque'), ('inactive', 'Inativo')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhonesInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phones_count', models.IntegerField()),
                ('phones_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhonesNumberInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phones_line_count', models.IntegerField()),
                ('phones_line_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('in_stock', 'Estoque'), ('inactive', 'Inativo')], max_length=20)),
                ('state', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Bom'), ('regular', 'Regular'), ('bad', 'Ruim')], max_length=20)),
                ('serie_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_brand', to='brands.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phones_category', to='categories.category')),
                ('number', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phone_number', to='phones.phonenumber')),
            ],
            options={
                'ordering': ['-model'],
            },
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_operator', to='phones.phoneoperator'),
        ),
    ]
