# Generated by Django 5.1.2 on 2024-10-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneoperator',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
