# Generated by Django 5.1.2 on 2024-10-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phoneoperator_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
