# Generated by Django 5.1.2 on 2024-10-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_alter_phone_status_alter_phonenumber_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='state',
        ),
    ]
