# Generated by Django 5.1.2 on 2024-10-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_remove_phone_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
