# Generated by Django 5.1.2 on 2024-10-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_phone_inventory_number_phone_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
