# Generated by Django 5.1.2 on 2024-11-23 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_equipament_count'),
        ('phones', '0010_alter_phone_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='category',
            field=models.ForeignKey(default='Telefone', on_delete=django.db.models.deletion.PROTECT, related_name='phones_category', to='categories.category'),
        ),
    ]
