# Generated by Django 5.1.2 on 2024-12-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0012_alter_phone_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesinventory',
            name='phones_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phonesinventory',
            name='phones_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='phonesnumberinventory',
            name='phones_line_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phonesnumberinventory',
            name='phones_line_value',
            field=models.FloatField(default=0),
        ),
    ]
