# Generated by Django 5.1.2 on 2024-12-09 23:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0014_alter_phonenumber_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR'),
        ),
    ]
