# Generated by Django 5.1.2 on 2024-10-16 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputersInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computers_count', models.IntegerField()),
                ('computers_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('in_stock', 'Estoque'), ('inactive', 'Inativo')], max_length=20)),
                ('state', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Bom'), ('regular', 'Regular'), ('bad', 'Ruim')], max_length=20)),
                ('serie_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('memory_ram', models.CharField(blank=True, choices=[('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB')], max_length=10, null=True)),
                ('storage', models.CharField(blank=True, choices=[('128GB SSD', '128GB SSD'), ('256GB SSD', '256GB SSD'), ('480GB SSD', '480GB SSD'), ('512GB SSD', '512GB SSD'), ('1TB SSD', '1TB SSD'), ('128GB HD', '128GB HD'), ('256GB HD', '256GB HD'), ('480GB HD', '480GB HD'), ('512GB HD', '512GB HD'), ('1TB HDD', '1TB HDD')], max_length=10, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computer_brand', to='brands.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computer_category', to='categories.category')),
            ],
            options={
                'ordering': ['-model'],
            },
        ),
    ]
