# Generated by Django 5.1.2 on 2024-10-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_alter_computer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
