# Generated by Django 5.1.2 on 2024-10-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_computer_inventory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
