# Generated by Django 5.1.2 on 2024-10-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0005_alter_computer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
