# Generated by Django 5.1.2 on 2024-10-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0006_computer_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='state',
        ),
    ]
