# Generated by Django 5.1.2 on 2024-12-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0008_alter_computer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computersinventory',
            name='computers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='computersinventory',
            name='computers_value',
            field=models.FloatField(default=0),
        ),
    ]
