# Generated by Django 5.1.2 on 2024-10-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='equipament_count',
            field=models.IntegerField(),
        ),
    ]
