# Generated by Django 5.1.2 on 2024-10-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_equipament_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='equipament_count',
            field=models.IntegerField(default=0),
        ),
    ]
