# Generated by Django 5.1.2 on 2024-10-19 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('in_stock', 'Estoque'), ('inactive', 'Inativo')], max_length=20)),
                ('state', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Bom'), ('regular', 'Regular'), ('bad', 'Ruim')], max_length=20)),
                ('address', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printers_brand', to='brands.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printers_category', to='categories.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printers_location', to='collaborators.sector')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
