# Generated by Django 5.1.2 on 2024-10-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0002_rename_serial_number_printer_serie_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintersInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printers_count', models.IntegerField()),
                ('printers_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
