# Generated by Django 5.1.2 on 2024-10-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_printersinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('in_stock', 'Estoque'), ('inactive', 'Inativo')], default='in_stock', max_length=20),
        ),
    ]
