# Generated by Django 5.1.2 on 2024-10-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0004_alter_printer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='state',
        ),
    ]
