# Generated by Django 5.1.2 on 2024-10-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0007_alter_printer_inventory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
