# Generated by Django 5.1.2 on 2024-11-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0008_alter_printer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['status']},
        ),
        migrations.AlterField(
            model_name='printer',
            name='serie_number',
            field=models.CharField(blank=True, default='0', max_length=50, unique=True),
        ),
    ]
