# Generated by Django 5.1.2 on 2024-12-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_equipament_count'),
        ('printers', '0012_alter_printersinventory_printers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='category',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.PROTECT, related_name='printers_category', to='categories.category'),
        ),
    ]
