# Generated by Django 5.1.2 on 2024-10-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='License',
        ),
        migrations.DeleteModel(
            name='LicenseType',
        ),
    ]
