# Generated by Django 5.1.2 on 2024-10-16 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['-software']},
        ),
    ]
