# Generated by Django 5.1.2 on 2024-10-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_alter_license_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='name',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
