# Generated by Django 5.1.2 on 2024-10-23 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('licenses', '0007_license_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_category', to='categories.category'),
        ),
    ]
