# Generated by Django 5.1.2 on 2024-10-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0008_alter_license_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensesInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenses_count', models.IntegerField()),
                ('licenses_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
