# Generated by Django 5.1.2 on 2024-10-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0010_license_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
