# Generated by Django 5.1.2 on 2024-10-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0012_alter_license_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='license',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
