# Generated by Django 5.1.2 on 2024-10-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0013_alter_license_options_license_inventory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
