# Generated by Django 5.1.2 on 2024-11-23 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_equipament_count'),
        ('licenses', '0016_alter_license_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='category',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.PROTECT, related_name='license_category', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateField(blank=True, default='2000-12-12'),
        ),
        migrations.AlterField(
            model_name='license',
            name='purchase_date',
            field=models.DateField(blank=True, default='2000-12-12'),
        ),
    ]
