# Generated by Django 5.1.2 on 2024-11-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0017_alter_license_category_alter_license_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='purchase_date',
            field=models.DateField(blank=True),
        ),
    ]
