# Generated by Django 5.1.2 on 2024-12-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0019_alter_license_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensesinventory',
            name='licenses_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='licensesinventory',
            name='licenses_value',
            field=models.FloatField(default=0),
        ),
    ]
